"""empty message

Revision ID: feb5dccf2da7
Revises: 
Create Date: 2020-07-29 15:56:25.182137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb5dccf2da7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('deletion_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_creation_date'), 'link', ['creation_date'], unique=False)
    op.create_index(op.f('ix_link_deletion_date'), 'link', ['deletion_date'], unique=False)
    op.create_table('process',
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('deletion_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('parent_process_id', sa.Integer(), nullable=True),
    sa.Column('is_abstract', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_creation_date'), 'process', ['creation_date'], unique=False)
    op.create_index(op.f('ix_process_deletion_date'), 'process', ['deletion_date'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('product',
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('deletion_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_creation_date'), 'product', ['creation_date'], unique=False)
    op.create_index(op.f('ix_product_deletion_date'), 'product', ['deletion_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_deletion_date'), table_name='product')
    op.drop_index(op.f('ix_product_creation_date'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_process_deletion_date'), table_name='process')
    op.drop_index(op.f('ix_process_creation_date'), table_name='process')
    op.drop_table('process')
    op.drop_index(op.f('ix_link_deletion_date'), table_name='link')
    op.drop_index(op.f('ix_link_creation_date'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
